version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.1
  node: circleci/node@6.2.0
  serverless-framework: circleci/serverless-framework@2.0.2
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Check Node Version
          command: |
            node --version
      - run:
          name: Print me
          command: echo "Hello World!"
  deploy:
    executor: serverless-framework/setup
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - serverless/setup:
          provider: AWS
          app-name: serverless-framework-orb
          org-name: circleci
      # - run:
      #     name: Local invoke add function
      #     command: serverless invoke local --function add --path 'sampleData/data.json'
      - run:
          name: deploy
          command: serverless deploy -v
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t demo_nodejs_webpage -t sourav673/demo_nodejs_webpage7 .
            echo $DOCKER_PASSWORD | docker login -u sourav673 --password-stdin
            docker push sourav673/demo_nodejs_webpage7:latest

workflows:
  build_test:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
              branches:
                only: develop-circleci
          context: serverless-framework-orb-testing
      - build_docker_image



